import './globals.css';
import type { Metadata } from 'next';
import { inter } from './fonts';
import { Navbar } from '@/components/Navbar';
import ReduxProvider from '@/redux/provider';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }): JSX.Element {
  return (
    <html lang="en" className={inter.className}>
      <body className='bg-background'>
        <ReduxProvider>
          <header>
            <Navbar />
          </header>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
